// src/renderer/src/components/copyright-info.tsx
import { Copyright } from 'lucide-react'

export default function CopyrightInfo(): JSX.Element {
  return (
    <footer className="flex scale-90 items-center justify-center gap-1.5 py-2 text-xs text-slate-500">
      <Copyright size={14} aria-hidden="true" />
      <span>hangtiancheng</span>
    </footer>
  )
}

// src/renderer/src/components/copyright-info.vue
<script setup lang="ts">
import { Github } from '@icon-park/vue-next'
</script>

<template>
  <!-- items-center 单行, 侧轴中点对齐, 这里是垂直居中 -->
  <main class="flex scale-90 items-center justify-center text-xs text-slate-500 opacity-80">
    <Github theme="outline" />
    <div class="ml-1">hangtiancheng</div>
  </main>
</template>

<style scoped lang="css"></style>
