// src/renderer/src/components/floor-buttons.tsx
import { Button } from 'antd'
import { stopConvert, useConvertStore } from '../hooks/use-convert'
import { removeAll, resetAll } from '../hooks/use-video'

export default function FloorButtons(): JSX.Element {
  const isConverting = useConvertStore((s) => s.isConverting)

  return (
    <section className="flex justify-center gap-2">
      <Button size="small" type="primary" onClick={stopConvert}>
        结束转码
      </Button>
      <Button size="small" danger disabled={isConverting} onClick={removeAll}>
        全部清空
      </Button>
      <Button size="small" disabled={isConverting} onClick={resetAll}>
        全部重置
      </Button>
    </section>
  )
}

// src/renderer/src/components/floor-buttons.vue
<script setup lang="ts">
import { ElButton } from 'element-plus'
import { useConvert, useVideo } from '@renderer/composables'

const { removeAll, resetAll } = useVideo()
const { isConverting } = useConvert()

function stop() {
  window.api.stop()
}
</script>

<template>
  <main class="flex justify-center">
    <ElButton type="primary" size="small" @click="stop">结束转码</ElButton>
    <ElButton type="danger" size="small" :disabled="isConverting" @click="removeAll"
      >全部清空</ElButton
    >
    <ElButton type="warning" size="small" :disabled="isConverting" @click="resetAll"
      >全部重置</ElButton
    >
  </main>
</template>

<style scoped lang="scss"></style>
