// src/renderer/src/components/video-list.vue
<script setup lang="ts">
import { ElScrollbar } from 'element-plus'
import VideoItem from './video-item.vue'
import { useVideoStore } from '@renderer/store'
import { storeToRefs } from 'pinia'
const videoStore = useVideoStore()
const { videoList } = storeToRefs(videoStore)
</script>

<template>
  <main class="h-80 overflow-y-auto">
    <!-- v-if 比 v-for 的优先级更高 -->
    <!-- eslint: This 'v-if' should be moved to the wrapper element. -->
    <ElScrollbar v-if="videoList.length">
      <VideoItem
        v-for="(videoItem, idx) of videoList"
        :key="videoItem.filepath"
        :video-item="videoItem"
        :idx="idx"
      />
    </ElScrollbar>
    <div v-else class="text-center text-xs text-slate-600 opacity-80">请添加视频</div>
  </main>
</template>

<style scoped lang="scss"></style>

// src/renderer/src/components/video-list.tsx
import { useVideoStore } from '../store/use-video-store'
import VideoItem from './video-item'

export default function VideoList(): JSX.Element {
  const videoList = useVideoStore((s) => s.videoList)

  if (videoList.length === 0) {
    return (
      <div className="flex h-80 items-center justify-center rounded-xl border border-dashed border-ink-600 text-xs text-slate-500">
        请添加视频
      </div>
    )
  }

  return (
    <ul className="m-0 flex h-80 list-none flex-col gap-1.5 overflow-y-auto p-0 pr-0.5">
      {videoList.map((video, idx) => (
        <VideoItem key={video.filepath} video={video} idx={idx} />
      ))}
    </ul>
  )
}
